info:
  component: Config Server

spring:
  application:
    name: configserver
  autoconfigure.exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  jmx:
    default_domain: cloud.config.server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jfuentesve/spring-cloud-props
          repos:
            - patterns: multi-repo-demo-*
              uri: https://github.com/jfuentesve/spring-cloud-props
server:
  port: 8888
management:
  endpoints:
    web:
      base-path: /admin
